### ISSUE TITLE
Check: attributeNames match column names

### ISSUE THREAD

**Issue by eeerika** [NCEAS/metadig-rake#5]
## Purpose

This check will look to see if documented attributeNames of a file match the column names in the data (in value and order).

## Components

File name, used to read in the file data/access the dataTable metadata and retrieve:
1. a list of the attributeNames (metadata)
2. a list of the column names (data)

## Result

SUCCESS: if all of the attributeNames match the column names (value and order)
FAILURE: if there is one or more difference (would be good if it showed the difference)
ERROR: on system error or exception in the check code, representing a bug in the check system

**Comment by jeanetteclark** [comment]
moved to https://github.com/NCEAS/metadig-checks/issues/449
