### ISSUE TITLE
Check: missingValueCodes fully documented

### ISSUE THREAD

**Issue by eeerika** [NCEAS/metadig-rake#6]
## Purpose

This check will look to see if documented missingValueCodes of a file match the codes present in the data.

## Components

- list of common missing value codes
- data file name, in order to:
1. find the missing value codes documented for the file in the metadata
2. read in the data to look at values in each column and compare them to common missing value codes/what was documented
- also check columns for type mismatches for potential missing value codes that weren't detected from the list of common ones

## Result

SUCCESS: if all of the missing value codes found in a file are present in the missingValueCode sections for each applicable column
FAILURE: if there is one or more difference (would be good if it showed the difference: what code and for which columns)
ERROR: on system error or exception in the check code, representing a bug in the check system

**Comment by mbjones** [comment]
This sounds good. It is also often useful to look for type mismatches, which often represent missing value codes that are defined. E.g., in a column of type `double` with values like `1.2,2.1,3.4,NA,3.4,FAIL,4.5,2.2,POWER,1.1,2.2` the string values probably represent error conditions or missing values.

**Comment by jeanetteclark** [comment]
moved to https://github.com/NCEAS/metadig-checks/issues/452
