### ISSUE TITLE
Check: physical checksum matches data file checksum

### ISSUE THREAD

**Issue by eeerika** [NCEAS/metadig-rake#7]
## Purpose

This check will look to see if the checksum listed in the physical section of the metadata matches the data file's checksum.

## Components

- checksum (authentication) from physical section
- checksum from data file itself

## Result

SUCCESS: if the two checksums match
FAILURE: if the two checksums do not match
ERROR: on system error or exception in the check code, representing a bug in the check system

**Comment by jeanetteclark** [comment]
implemented over in metadig-checks
