### ISSUE TITLE
Check: physical size matches data file size

### ISSUE THREAD

**Issue by eeerika** [NCEAS/metadig-rake#8]
## Purpose

This check will look to see if the size listed in the physical section of the metadata matches the data file's size.

## Components

- size from physical section
- byte size from data file itself

## Result

SUCCESS: if the two sizes match
FAILURE: if the two sizes do not match
ERROR: on system error or exception in the check code, representing a bug in the check system

**Comment by jeanetteclark** [comment]
moved to https://github.com/NCEAS/metadig-checks/issues/451
